import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full w-full">
      <body
        className={`${notoSans.variable} antialiased flex justify-center items-center bg-gray-100`}
      >
        <div className="w-[600px] min-h-screen bg-white shadow-lg overflow-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
